title: Marse | Zone
author: Marse Lau
email: marseis@163.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog site.

# social links
github_username:  marseis # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
